export * from './ir/types.js'
export { SemanticAnalyzer } from './ir/analyzer.js'
export { BrowserSession, analyze, explain } from './browserIR/session.js'
export { EngineManager } from './daemon/engines.js'
export { loadConfig } from './config/index.js'
export { FlowDetector } from './engines/flow-detector.js'
export type { DetectedFlow } from './engines/flow-detector.js'
export { TestRunner } from './engines/test-runner.js'
export type { TestCase, TestResult } from './engines/test-runner.js'
export { VisualDiffEngine } from './engines/visual-diff.js'
export type { VisualDiffResult } from './engines/visual-diff.js'
export { FailureAnalyzer } from './engines/failure-analyzer.js'
export type { FailureContext, AnalysisResult } from './engines/failure-analyzer.js'
export { NetworkCapture } from './engines/network-capture.js'
export type { NetworkEntry } from './engines/network-capture.js'
export { ConsoleCapture } from './engines/console-capture.js'
export type { ConsoleEntry, ErrorEntry } from './engines/console-capture.js'
export { ScriptInjection } from './engines/script-injection.js'
export { StateManager } from './engines/state-manager.js'
export { ElementHighlight } from './engines/element-highlight.js'
export { classifyInputs, guessInputValue } from './engines/dom-extractor.js'
export type { ClassifiedElements, DOMElement } from './engines/dom-extractor.js'
